### ISSUE TITLE
Unable to parse body below the multiple new line 

### ISSUE THREAD

**Issue by ayushlodhi001** [mikel/mail#1096]
I am facing this problem that whenever there are multiple new lines in the mail, then the mail mail gem do not parse the data below that line 

```
In-Reply-To: <0100015bdd4f4b11-a4a7f4b5-ffa6-4d87-b8cb-62ceb22b4810-000000@email.amazonses.com>
References: <> <0100015bdd4f4b11-a4a7f4b5-ffa6-4d87-b8cb-62ceb22b4810-000000@email.amazonses.com>
X-Disclaimed: 17206
To: ops@abc.in
Cc: xyzs@abc.in
MIME-Version: 1.0
Subject: subject text
 
X-KeepSent: 60DAC3E8:D178BEE1-6525811A:0016C012;
 type=4; name=$KeepSent
X-Mailer: Lotus Notes Release 8.0.1 February 07, 2008
From: Yogesh.Sawant@dachser.co.in
Message-ID: <OF60DAC3E8.D178BEE1-ON6525811A.0016C012-6525811A.0016D1AB@asd.co.in>
Date: Mon, 8 May 2017 09:37:47 +0530
X-MIMETrack: Serialize by Router on DIPLDOM02/SVR/Dachser(Release 8.0.2|August 07, 2008) at
```

**In the above example it won't parse data below the subject**

**Comment by jeremy** [comment]
Fixed by #539. This is due to the Subject header continuing onto a new line, but only containing whitespace on that line.

**Comment by ayushlodhi001** [comment]
@jeremy So what is the solution for that? I am still facing this issue.

**Comment by ayushlodhi001** [comment]
@jeremy Thanks :)
