### ISSUE TITLE
Mail 2.7.0 NameError: uninitialized constant Mail::PhraseListsElement

### ISSUE THREAD

**Issue by gc-olivierho** [mikel/mail#1238]
Hi,
When running some code (Redmine mail reception, after modifying the mail dependency to 2.7.0 instead of 2.6.4), I got the following error:

NameError: uninitialized constant Mail::PhraseListsElement
/usr/local/bundle/gems/mail-2.7.0/lib/mail/parsers/phrase_lists_parser.rb:885:in `parse'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/elements/phrase_list.rb:11:in `initialize'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/fields/keywords_field.rb:24:in `new'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/fields/keywords_field.rb:24:in `phrase_list'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/fields/keywords_field.rb:28:in `keywords'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/fields/keywords_field.rb:32:in `encoded'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/field.rb:237:in `method_missing'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/header.rb:213:in `block in encoded'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/header.rb:212:in `each'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/header.rb:212:in `encoded'
/usr/local/bundle/gems/mail-2.7.0/lib/mail/message.rb:1831:in `encoded'

Note that this is fixed in the current trunk version (in November 2017), but 2.7.0 is still the latest available release.

**Comment by jeremy** [comment]
Fixed in 2.7.1.rc1 gem!

**Comment by gc-olivierho** [comment]
I'm really sorry, but 2.7.1.rc1 does not contain the fix of the trunk..., it still contains 
        raise Mail::Field::IncompleteParseError.new(Mail::PhraseListsElement, data, p)
at the end of phrase_lists_parser.rb, unlike the trunk version of that file :( .
I confirmed this by running 
gem uninstall mail -v  '2.7.0'
gem update mail --prerelease
bundle update mail
and running my function, and it still fails with the nameError exception.

**Comment by rlue** [comment]
I can confirm that this bug still exists in 2.7.1.rc1.

To reproduce: save [this gist](https://gist.githubusercontent.com/rlue/c5082ff6e46dcd55eadf4087d69faae4/raw/bb73440f11d3631aaa24a5cbf291844f9a95d6d6/1238_sample_mail). Then,

```ruby
>> Mail.new(File.read('path/to/saved/gist')).html_part.body.decoded
Mail::UnknownEncodingType: Don't know how to decode utf-8, please call #encoded and decode it yourself.
from /home/rlue/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mail-2.7.1.rc1/lib/mail/body.rb:176:in `decoded'
```

I have also confirmed that this error doesn't occur on the `master` version of the gem. Any chance we'll see an updated release that incorporates the fix currently in trunk soon?

**Comment by rlue** [comment]
Pinging @jeremy, what is the status of this issue?

**Comment by rlue** [comment]
Tbh I don't have a clue. And I don't really understand my first comment on this thread, because the error message is totally different from @gc-olivierho's – though they both seem to involve the `#encoded` method? -_-'

FWIW, homeboy did say this issue was fixed in Nov. 2017, and there were only [19 commits made in that time period](https://github.com/mikel/mail/commits/master?after=38b27ba0a786ed4f830847d4e797e452aa4a0b4a+0) (starting with 81f7d83), so maybe that narrows it down?
