### ISSUE TITLE
Problem with frozen strings

### ISSUE THREAD

**Issue by aried3r** [mikel/mail#965]
Even after #951 I have problems using this gem because of [this method](https://github.com/mikel/mail/blob/728942f2bc3a24fc84d6653e80d842b08a8858a0/lib/mail/utilities.rb#L23-L37) at least. The problem is `.force_encoding` which tries to modify `self`. So I guess we should `.dup` the string before modifying?

Stack trace calling `.format` on `Mail::Address`
```
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mail-2.6.3/lib/mail/utilities.rb:22:in `force_encoding': can't modify frozen String (RuntimeError)
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mail-2.6.3/lib/mail/utilities.rb:22:in `quote_phrase'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mail-2.6.3/lib/mail/elements/address.rb:51:in `format'
```

**Comment by jeremy** [comment]
+1 to not mutating its argument. Could you write up the change + a test?

**Comment by aried3r** [comment]
Fixed in 2.6.4. Thanks!

**Comment by MaxPleaner** [comment]
I'm still getting `*** RuntimeError Exception: can't modify frozen String` for any of the commands to fetch email from a Gmail account. e.g. `Mail.first` or `Mail.all`.

I have in my Gemfile.lock mail (2.6.6) and Ruby 2.5.0-dev

I never added the frozen string literal: true comment either, by the way.

**Comment by jeremy** [comment]
@MaxPleaner Do you have a full backtrace for the exception? Thanks!

**Comment by sungsong88** [comment]
@jeremy I have the same issue... How can I grab a backtrace please? I'll post it here.
